remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
logo: "https://avatars.githubusercontent.com/u/28387557?s=200&v=4"


title: Nextome SDK Documentation
email: info@nextome.net
description: >- # this means to ignore newlines until "baseurl:"
  Nextome SDK Documentation
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://nextome.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  
 defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
    values:
      layout: "default"
