site_name: Nextome Documentation
theme: 
  name: material
  logo: assets/logo-white.svg
  favicon: material/library
  features:
    - navigation.sections
    - content.code.annotate 
#    - navigation.expand


  palette:
    scheme: youtube
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
        alternate_style: true

extra:
  version:
    provider: mike

nav:
    - 'Introduction': 'index.md'
    - 'Flutter Map':
        - 'Changelog': 'Flutter Map/index.md'
    - 'Nextome SDK':
        - 'Introduction': 'Nextome SDK/introduction.md'
        - 'Android': 
          - 'Android Integration': 'Nextome SDK/Android/integration.md'
          - 'Android Changelog': 'Nextome SDK/Android/changelog.md'
        - 'iOS': 
          - 'iOS Integration': 'Nextome SDK/iOS/integration.md'
          - 'iOS Changelog': 'Nextome SDK/iOS/changelog.md'